version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  assignees:
  - sue445
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: activerecord
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
