# 自動生成されるものはチェック対象から除外する
AllCops:
  Exclude:
    - "vendor/**/*" # rubocop config/default.yml
    - "db/schema.rb"
# TODO: require rubocop > 0.28.0
#  DisplayCopNames: true

##################### Style ##################################

Style/AndOr:
  EnforcedStyle: conditionals

Style/AsciiComments:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/DeprecatedHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FormatString:
  EnforcedStyle: percent

Style/GuardClause:
  MinBodyLength: 5

Style/HashSyntax:
  Exclude:
    - "**/*.rake"

Style/IfUnlessModifier:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 6

Style/PredicateName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/RegexpLiteral:
  MaxSlashes: 0

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

##################### Lint ##################################

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*.rb"

Metrics/PerceivedComplexity:
  Max: 8
