version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile
  heroku:    circleci/heroku@0.0.2

executors:
  default:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RACK_ENV: test
      - image: circleci/postgres:9.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""
      - image: memcached:1.5
    working_directory: ~/app

jobs:
  rspec:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v2-bundle"

      - run: cp .circleci/database.yml config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake ar:migrate:reset
      - run: bundle exec rake groonga:setup
      - run: bundle exec rspec

  rubocop:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v2-bundle"

      - run: bundle exec rubocop

  deploy:
    docker:
      - image: sue445/heroku-cli
    working_directory: /home/circleci/app

    steps:
      - checkout
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "73:07:eb:35:06:58:6f:da:9d:7a:9b:f5:64:08:41:d3"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
      - rubocop
      - deploy:
          context: Heroku
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
