version: 2.0

default: &default
  docker:
    - image: circleci/ruby:2.5.1
      environment:
        RACK_ENV: test
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: circle_test
        POSTGRES_PASSWORD: ""
    - image: memcached:1.5
  working_directory: ~/app

save_bundle_cache_option: &save_bundle_cache_option
  key: v1-bundle-{{ checksum "Gemfile.lock" }}
  paths:
    - ~/app/vendor/bundle

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v1-bundle-{{ checksum "Gemfile.lock" }}
    - v1-bundle

jobs:
  rspec:
    <<: *default

    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup_bundle.sh
      - save_cache:
          <<: *save_bundle_cache_option

      - run: cp .circleci/database.yml config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake ar:migrate:reset
      - run: bundle exec rake groonga:setup
      - run: bundle exec rspec

  rubocop:
    <<: *default

    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup_bundle.sh
      - save_cache:
          <<: *save_bundle_cache_option

      - run: bundle exec rubocop

  deploy:
    docker:
      - image: sue445/heroku-cli
    working_directory: /home/circleci/app

    steps:
      - checkout
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "73:07:eb:35:06:58:6f:da:9d:7a:9b:f5:64:08:41:d3"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
      - rubocop
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
