version: 2.0

default: &default
  docker:
    - image: circleci/ruby:2.5.0-node
      environment:
        RACK_ENV: test
    - image: circleci/postgres:9.5-alpine
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: circle_test
        POSTGRES_PASSWORD: ""
    - image: memcached:1.5
  working_directory: ~/app

jobs:
  checkout_code:
    <<: *default

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle_dependencies:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Environment.CIRCLE_BRANCH }}
            - v1-bundle-master
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle clean
      - save_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_BRANCH }}
          paths:
            - ~/app/vendor/bundle

  rspec:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_BRANCH }}
      - run: bundle --path vendor/bundle
      - run: cp .circleci/database.yml config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rake ar:migrate:reset
      - run: bundle exec rake groonga:setup
      - run: bundle exec rspec

  rubocop:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_BRANCH }}
      - run: bundle --path vendor/bundle
      - run: bundle exec rubocop

  deploy:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "73:07:eb:35:06:58:6f:da:9d:7a:9b:f5:64:08:41:d3"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
