development:
  adapter: sqlite3
  database: db/sebastian_development.db

test:
  adapter: sqlite3
  database: db/sebastian_test.db

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>
